### ISSUE TITLE
Not actually downloadable yet?

### ISSUE THREAD

**Issue by D3SL** [TeamJM/journeymap-webmap#1]
Just checking if this is intentional as the "mods" are several months old on modrinth and curseforge.

**Comment by mysticdrew** [comment]
> Just checking if this is intentional as the "mods" are several months old on modrinth and curseforge.

Ha, sorry, I just noticed this. I do not have notifications or any webhooks set up for this repo yet. 
This is not in use yet, nor usable with any released versions of JourneyMap it will be compatible with JourneyMap 6.0.0 when I release that.
