### ISSUE TITLE
How do I use this on my server (install server-side)?

### ISSUE THREAD

**Issue by b1bradders** [TeamJM/journeymap-webmap#2]
I don't see any config. options in Admin Settings, and JourneyMap Web isn't making any configs files.

Please help!

**Comment by mysticdrew** [comment]
Read the mod description

**Comment by mysticdrew** [comment]
![image](https://github.com/TeamJM/journeymap-webmap/assets/5459941/868f2401-483e-4863-9faf-2b01380719f5)

**Comment by b1bradders** [comment]
Oh, I'm really sorry. I didn't see that, even though I read it multiple times! 👍🏽
