### ISSUE TITLE
how to teleport by tags in the new version 1.21.1?

### ISSUE THREAD

**Issue by dangergengar** [TeamJM/journeymap-webmap#4]
![image](https://github.com/user-attachments/assets/2482b11a-ac0d-4b47-8e54-59407733588f)

how to teleport by tags in the new version 1.21.1? how to teleport by tags in the new version 1.21.1? I don't understand why I'm being asked to find a placemark on the map.

**Comment by mysticdrew** [comment]
?

wrong repo
