### ISSUE TITLE
Auto-Map glitches the whole client...?

### ISSUE THREAD

**Issue by ghost** [TeamJM/journeymap-webmap#6]
So, I'm using Journeymap v1.21.3-6.0.0-beta29 and whenever I go in the fullscreen map to use to auto-map (which I did once for its main purpose, and a second time to check if the bug reappeared, which it did), it just remove all color from the game and replaces it with black?? Except the ones for the map, minimap and the mod's own colors...?

Here are my computer specs (in case you need):
CPU: Ryzen 9 5900X
GPU: RTX 3060Ti
RAM: 16GB 3600MHz (6GB being allocated to MC)
All these with a 4K monitor, maybe that could be the cause, even tho I don't think it is

Are are all the mods I have (it's still vanilla MineCraft):
- Carpet
- Carpet TIS
- Clumps
- EntityCulling
- FerriteCore
- Iris (not used, just there)
- Item Scroller
- Journeymap
- Krypton
- Litematica
- MaLiLib
- MiniHUD
- Mod Menu
- Mouse Tweaks
- Sodium
- TweakerMore
- Tweakeroo
- Zoomify

I made a video to showcase this because it's kinda weird, I don't know if it's the whole mod or "just" my computer doing this
You can watch the video on YouTube there: https://youtu.be/-bcrF70-fXs (could not attach it to the issue cause it's larger than 10MB)

In the video, I did `/tick freeze`, but it doesn't matter, it was just to avoid getting hit by a mob or whatever
Also, I tried reloading the texture packs, unsuccessfully.

**Comment by mysticdrew** [comment]
Wrong issue tracker, this is for the webmap
